// aggregare funtions


// 1.Add Field
// This wll temporarily store the key value generated by addField

// db.scores.aggregate( [
//     {
//       $addFields: {
//         totalHomework: { $sum: "$homework" } ,
//         totalQuiz: { $sum: "$quiz" }
//       }
//     },
//     {
//       $addFields: { totalScore:
//         { $add: [ "$totalHomework", "$totalQuiz", "$extraCredit" ] } 
//      }
//     }
//  ] )

// 2.Bucket 
// Based on GroupBy, boundaries we can gather the output into a single group.

// db.getCollection('artist').aggregate([
//     //first stage
//     {
//         $bucket:{
//             groupBy: "$year_born",
//             boundaries: [1840,1850,1860,1870,1880],
//             default:"Other",
//             output:{
//                 "count": {$sum:1},
//                 "artist":{
//                     $push:{
//                         "name": {$concat:["$first_name"," ","$last_name"]},
//                         "year_born":"$year_born"
//                     }
//                 }
//             }
//         }
//     },
//     //second stage
//     {
//         $match: {count: {$gt:3}}
//     }
// ])


//